### ISSUE TITLE
Seroxen RAT Uni.bat Payload

### ISSUE THREAD

**Issue by BYT3W1Z4RD** [flyingchiken/uni.bat#1]
Is this a payload from an older version or seroxen? The obfuscation is less in depth and the detection rate is higher than the most recent payloads.
Either way, this is malware.

**Comment by flyingchiken** [comment]
yea i know, i just upload malware on git hub and i never asked anyone to download it, its just for personal use only

**Comment by flyingchiken** [comment]
and yes this is an  older version or seroxen

**Comment by flyingchiken** [comment]
i use seroxen for pen testing and other uses, kind of forgot i left this
